import textwrap

def generate_dummy_characters(characters, dnas):
	dummy_characters = []
	prefix = textwrap.dedent(f"""
		# Canon Children Dummy Characters
		# Generated by Canon Children tool (@yeru)
		# Do not edit this file directly, it will be overwritten
	""").lstrip()

	for child_id, child in characters.items():
		if child_id in dnas:
			dummy_characters.append(create_dummy_character(child))

	return prefix + '\n' + ''.join(dummy_characters).lstrip()

def create_dummy_character(child):
	return textwrap.dedent(f"""
		Dummy_{child["id"]} = {{
			name = {child["name"]["primary"]}
			dna = {child["id"]}
			religion = fots_seven
			culture = northman
			father = Ruin_Empress
			118.1.1 = {{
				birth = yes
				add_character_flag = has_scripted_appearance
			}}
			118.1.2 = {{ death = yes }}
		}}
	""")