import textwrap

def generate_traits(ids: list) -> str:
	traits = []
	prefix = textwrap.dedent(f"""
		# Canon Children Traits
		# Generated by Canon Children tool (@yeru)
		# Do not edit this file directly, it will be overwritten
	""").lstrip()

	for character_id in ids:
		trait = textwrap.dedent(f"""
			is_{character_id.lower()} = {{
				physical = no
				shown_in_ruler_designer = no
				name = trait_hidden
				desc = trait_hidden_desc
				icon = pure_blooded.dds
			}}
		""")

		traits.append(trait)

	return prefix + '\n' + ''.join(traits).strip()